server:
  port: 8080

spring:
  data.mongodb.uri: mongodb://localhost:27017/data-test

logging:
  level:
    root: INFO
    org.springframework.data: TRACE
  pattern.console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{0}: %msg%n"
